blog/urls.py
from django.urls import path
from . import views

app_name='blog'

urlpatterns = [
    path('',views.all_blogs,name='all_blogs'),
    path('<int:blog_id>/',views.detail,name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blog(models.Model):
    title=models.CharField(max_length=200)
    date=models.DateField()
    desc=models.TextField()
    
    def __str__(self):
        return self.title
    

portfolio/models.py
from django.db import models

class Project(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='portfolio/images/')
    url=models.URLField(blank=True)  

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from.models import Blog

def all_blogs(request):
     blogs=Blog.objects.order_by('-date')
     return render(request,
                   'blog/all_blogs.html',
                   {'blogs':blogs})
def detail(request,blog_id):
     blog=get_object_or_404(Blog, pk=blog_id)
     return render(request,'blog/detail.html',{'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects=Project.objects.all()
    return render(request,'portfolio/home.html',{'projects':projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/base.html'%}

{% block content %}

<h1>Blogs</h1>
<h2>Aditya has written {{blogs.count}} blogs {{blogs.count|pluralize}}</h2>
{%for blog in blogs %}

<a href="{% url 'blog:detail' blog.id %}"><h2>{{blog.title}}</h2></a>
<h5>{{blog.date|date:'M d Y'|upper}}</h5>
<p>{{blog.desc|safe|striptags|truncatechars:100}}</p>

{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/base.html'%}

{% block content %}
<h1>{{blog.title}}</h1>

<h3>--{{blog.date|date:"F jS Y"}}--</h3>

<h4>{{blog.desc|safe|striptags}}</h4>
{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  </head>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}{% endblock %}
  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.min.js" integrity="sha384-Rx+T1VzGupg4BHQYs2gCW9It+akI2MM/mndMCy36UVfodzcJcF0GGLxZIzObiEfa" crossorigin="anonymous"></script>
  </body>  
</html>

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html'%}

{% block content %}
    <h2>ADITYA'S PORTFOLIO</h2>
    {% load static %}
    <br>
    <a href="{%url 'blog:all_blogs' %}">Blog</a>
    <br>
    <a href="{% static 'portfolio/Resume.pdf' %}">Resume</a>
    <br>
    <img src="{% static 'portfolio/158143.jpg' %}">

    {% for project in projects %} 
    <h2>{{project.title}}</h2>
    <p>{{project.description}}</p>
    <img src="{{ project.image.url }}" height=70 width="80">
    {%if project.url %}
    <br><a href="{{project.url}}">Link</a>
    {% endif %}
    {% endfor %}
    <br>
{% endblock %}